language: scala

scala:
  - 2.12.4
  - 2.11.12

env:
  - JDK=oraclejdk8
  - JDK=openjdk6

before_script:
  - jdk_switcher use $JDK

matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.4
      env: JDK=openjdk6
